In [5]:
import numpy as np


def perceptron_with_bias(data_points, labels, max_passes=10):
    X = np.array(data_points)
    y = np.array(labels)

    theta = np.zeros(2)
    theta_0 = 0.0
    progression = []

    for _ in range(max_passes):
        mistake_made = False 
        for i in range(len(X)):
            if y[i] * (np.dot(theta, X[i]) + theta_0) <= 0:
                theta += y[i] * X[i]
                theta_0 += y[i]
                progression.append(theta.copy())
                mistake_made = True

        if not mistake_made:
            break

    return theta.tolist(), theta_0, progression

In [6]:
data_points = [[-4, 2], [-2, 1], [-1, -1], [2, 2], [1, -2]]
labels = [1, 1, -1, -1, -1]

final_theta, final_theta_0, progression = perceptron_with_bias(data_points, labels)
final_theta, final_theta_0, progression

([-3.0, 3.0],
 np.float64(-3.0),
 [array([-4.,  2.]),
  array([-3.,  3.]),
  array([-5.,  1.]),
  array([-4.,  2.]),
  array([-3.,  3.])])